[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[phases.postbuild]
cmds = ['npm prune --production', 'npm install vite esbuild @vitejs/plugin-react']

[start]
cmd = 'npm run start'