// This file will be auto-generated by Supabase CLI
// For now, we'll create a basic interface based on your schema

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          custom_identifier: string | null
          email_verified: boolean | null
          reset_token: string | null
          reset_token_expires: string | null
          last_login_at: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          custom_identifier?: string | null
          email_verified?: boolean | null
          reset_token?: string | null
          reset_token_expires?: string | null
          last_login_at?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          custom_identifier?: string | null
          email_verified?: boolean | null
          reset_token?: string | null
          reset_token_expires?: string | null
          last_login_at?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      dot_phrases: {
        Row: {
          id: number
          user_id: string
          trigger: string
          content: string
          description: string | null
          category: string | null
          share_code: string | null
          is_public: boolean | null
          shared_at: string | null
          import_count: number | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id: string
          trigger: string
          content: string
          description?: string | null
          category?: string | null
          share_code?: string | null
          is_public?: boolean | null
          shared_at?: string | null
          import_count?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: number
          user_id?: string
          trigger?: string
          content?: string
          description?: string | null
          category?: string | null
          share_code?: string | null
          is_public?: boolean | null
          shared_at?: string | null
          import_count?: number | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      ros_notes: {
        Row: {
          id: number
          user_id: string
          patient_name: string
          patient_dob: string
          patient_mrn: string
          selections: any // JSON
          medications: any // JSON
          generated_note: string
          created_at: string | null
        }
        Insert: {
          id?: number
          user_id: string
          patient_name: string
          patient_dob: string
          patient_mrn: string
          selections: any
          medications: any
          generated_note: string
          created_at?: string | null
        }
        Update: {
          id?: number
          user_id?: string
          patient_name?: string
          patient_dob?: string
          patient_mrn?: string
          selections?: any
          medications?: any
          generated_note?: string
          created_at?: string | null
        }
      }
      user_presets: {
        Row: {
          id: number
          user_id: string
          title: string
          is_favorite: boolean | null
          symptoms: any // JSON
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: number
          user_id: string
          title: string
          is_favorite?: boolean | null
          symptoms: any
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: number
          user_id?: string
          title?: string
          is_favorite?: boolean | null
          symptoms?: any
          created_at?: string | null
          updated_at?: string | null
        }
      }
      team_groups: {
        Row: {
          id: number
          name: string
          description: string | null
          created_by_user_id: string
          invite_code: string
          created_at: string | null
          expires_at: string
        }
        Insert: {
          id?: number
          name: string
          description?: string | null
          created_by_user_id: string
          invite_code: string
          created_at?: string | null
          expires_at: string
        }
        Update: {
          id?: number
          name?: string
          description?: string | null
          created_by_user_id?: string
          invite_code?: string
          created_at?: string | null
          expires_at?: string
        }
      }
      group_members: {
        Row: {
          id: number
          group_id: number
          user_id: string
          role: string
          joined_at: string | null
        }
        Insert: {
          id?: number
          group_id: number
          user_id: string
          role?: string
          joined_at?: string | null
        }
        Update: {
          id?: number
          group_id?: number
          user_id?: number
          role?: string
          joined_at?: string | null
        }
      }
      group_todos: {
        Row: {
          id: number
          group_id: number
          title: string
          description: string | null
          created_by_user_id: string
          status: string
          position: number
          assigned_to_user_id: string | null
          completed: boolean | null
          completed_by_user_id: string | null
          created_at: string | null
          completed_at: string | null
        }
        Insert: {
          id?: number
          group_id: number
          title: string
          description?: string | null
          created_by_user_id: string
          status?: string
          position?: number
          assigned_to_user_id?: string | null
          completed?: boolean | null
          completed_by_user_id?: string | null
          created_at?: string | null
          completed_at?: string | null
        }
        Update: {
          id?: number
          group_id?: number
          title?: string
          description?: string | null
          created_by_user_id?: string
          status?: string
          position?: number
          assigned_to_user_id?: string | null
          completed?: boolean | null
          completed_by_user_id?: string | null
          created_at?: string | null
          completed_at?: string | null
        }
      }
      group_events: {
        Row: {
          id: number
          group_id: number
          title: string
          description: string | null
          event_date: string
          created_by_user_id: string
          created_at: string | null
        }
        Insert: {
          id?: number
          group_id: number
          title: string
          description?: string | null
          event_date: string
          created_by_user_id: string
          created_at?: string | null
        }
        Update: {
          id?: number
          group_id?: number
          title?: string
          description?: string | null
          event_date?: string
          created_by_user_id?: string
          created_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}